/* ============================================================
   CASES — historical replay data layer
   Every number/name/coordinate carries a status:
     V = verified (primary/peer-reviewed source)
     A = approximate (best available / derived / gazetteer)
     S = simulated (generated for the prototype, NOT real)
   `src` indexes into the case's sources[] array.
   Nothing here is a prediction. These are public-data replays.
   ============================================================ */
const CASES = {

/* ================================================================== NEPAL */
np2026: {
  id:'np2026', short:'Nepal · Rasuwa 2026',
  title:'Rasuwa–Bhotekoshi Ice-Rock Avalanche & Debris Flood',
  country:'Nepal', hazard:'Ice-rock avalanche → temporary blockage → debris flood',
  hazardShort:'Ice-Rock Avalanche / Debris Flood',
  eventTime:'26 Aug 2026, 08:37 NPT', eventDate:'26 Aug 2026', tz:'NPT (UTC+5:45)',
  incidentId:'HKH-NP-2026-001',
  region:'Lhende Khola → Bhotekoshi → Trishuli, Rasuwa District',
  detectedChange:'Ice-rock detachment on the north face of Langtang Lirung; channel blockage in the Lhende Khola',
  changePct:'M5.2 landslide-source seismic signal',
  summary:'A slab of rock and glacier ice detached from the north face of Langtang Lirung (7,227 m) shortly after 08:37 NPT on 26 August 2026, fell about 1,200 m into the Lhende Khola on the Nepal–China border, briefly blocked the channel and released a sediment-laden debris flood down the Bhotekoshi and Trishuli. ICIMOD stresses this was an ice-rock avalanche cascade, not a classic glacial-lake outburst: no pre-existing lake has been shown to be the source, and DHM reported no heavy rainfall in Rasuwa immediately before the flood. The July 2025 Rasuwagadhi flood is precursor context only.',

  kpi:{ hazardStatus:'HIGH RISK', zoneFoot:'Rasuwa · Nuwakot · Dhading',
        areaKm2:{v:'≈40 km road corridor', s:'V', src:2},
        alerts:{v:'09', s:'V', src:2, foot:'NDRRMA situation reports issued'} },

  mparams:[
    {icon:'🏔️', label:'Glacier Geometry', status:'high',
     metrics:[['Source Peak','Langtang Lirung, 7,227 m'],['Detachment Elevation','≈5,200 m'],['Fall Height','≈1,200 m'],['Ice Thickness','No ground/radar survey available']],
     source:'ICIMOD field/satellite reconstruction of the 26 Aug 2026 detachment. Elevation and fall height as stated by ICIMOD — verified. Ice thickness: not measured.'},
    {icon:'❄️', label:'Ice / Snow', status:'high',
     metrics:[['Failure Type','Rock + glacier ice slab'],['Seismic Signature','M5.2, reclassified by USGS as landslide'],['Pre-existing Lake','None identified as source'],['Glacier Area (catchment)','≈4.6 km² — approximate']],
     source:'USGS reclassified the initially reported M4.4 earthquake as an M5.2 landslide source — verified. Glacier area is an approximate catchment estimate, not a measured inventory value.'},
    {icon:'🪨', label:'Crack & Instability', status:'high',
     metrics:[['Slope Failure','Confirmed on north face'],['Channel Blockage','Confirmed, Lhende Khola'],['Secondary Release','28 Aug 2026 barrier-lake breach']],
     source:'ICIMOD and CARE/ICIMOD reporting: a barrier lake formed by the initial debris broke on 28 August, briefly halting rescue in Nepal and China — verified.'},
    {icon:'💧', label:'Glacial Lakes', status:'high',
     metrics:[['Barrier Lake Area','0.11 km² (formed after the collapse)'],['Origin','Landslide-dammed, not glacial'],['Outlet Condition','Unstable — breached 28 Aug'],['Classification','NOT a classic GLOF']],
     source:'NDRRMA warned of continuing flood risk from an estimated 0.11 km² lake formed upstream by the blockage of the Lhende Khola (via WFP situation report) — verified. Any lake here is a temporary landslide-dammed lake, not a glacial lake.'},
    {icon:'🌊', label:'Hydrology', status:'high',
     metrics:[['River Rise at Galchhi','≈9 m in 30 minutes'],['Gauge Height, Galchhi','8.5 m'],['Gauges Destroyed','3 — Rasuwagadhi, Syabrubesi, Betrawati'],['Flood Volume at Devghat','57.4 million m³ (≈19.96 M m³ above base flow)'],['Travel Distance','Damage traced ≥100 km downstream']],
     source:'DHM gauge record and NDRRMA volume estimate, compiled in the ICIMOD/partner story map — verified. Galchhi is ≈88 km downstream of the source.'},
    {icon:'☁️', label:'Weather / Climate', status:'normal',
     metrics:[['Local Rainfall Trigger','Ruled out by DHM'],['Rainfall, Rasuwa','No substantial rain before the event'],['Tibetan-side Rainfall','Observed; contribution unclear'],['Temperature Anomaly','+2.0 °C — approximate']],
     source:'Nepal DHM reported no substantial rainfall in Rasuwa immediately before the flood — verified. This is the key reason investigators looked upstream. Temperature anomaly is an approximate regional figure, not a station measurement.'},
    {icon:'⛰️', label:'Terrain', status:'high',
     metrics:[['Headwall Slope','≈55° — approximate'],['Valley Form','Narrow, steep gorge'],['Deposition Point','Rasuwagadhi — first flat riverbed'],['Aspect','North-facing']],
     source:'ICIMOD explanation of why Rasuwagadhi and Timure were worst hit: the Lhende drops from over 5,000 m to about 1,800 m at the border, and the first flat ground is where the dry port, truck park and hydropower works were built — verified narrative; slope value approximate.'},
    {icon:'🌉', label:'Infrastructure', status:'high',
     metrics:[['Bridges Destroyed','>80'],['Road Damaged','≈40 km'],['Hydropower Damaged','13 projects (NEA); 14 energy facilities (WFP)'],['Capacity Off-Grid','≈431 MW'],['Key Sites','Rasuwagadhi, Chilime, Upper Trishuli 3A/3B, Trishuli, Devighat']],
     source:'WFP situation report (≈40 km roads, >80 bridges, ≥14 hydropower/energy facilities) and Nepal Electricity Authority (13 projects, ≈431 MW off-grid, ≈470 MW under construction damaged) — verified as reported.'},
    {icon:'🏘️', label:'Exposure', status:'high',
     metrics:[['Deaths (Nepal)','1,410 — as reported, still changing'],['Missing (Nepal)','6,145 — as reported'],['Deaths (Tibet AR, China)','43; 519 missing'],['Districts with Missing Persons','62'],['Border Crossing Traffic','>100,000 users in H1 2026']],
     source:'Figures as reported by NDRRMA / Nepal Police and compiled on the Wikipedia "2026 Nepal floods" index, retrieved 20 Sep 2026. Search, rescue and identification are ongoing — these numbers change and are NOT final.'},
    {icon:'🚑', label:'Response Resources', status:'anomaly',
     metrics:[['Security Personnel Mobilised','21,011'],['People Rescued','11,814'],['Foreign Nationals Rescued','253'],['Priority Areas','Syafru, Timure, NE Rasuwa'],['Hydropower Site Operations','Trishuli 3A, Haku Besi, Trishuli 3B, Chilime']],
     source:'NDRRMA Rasuwa–Bhotekoshi Search, Rescue and Relief Situation Report #01, 1 Sep 2026 — verified as reported on that date.'},
  ],

  ml:{ lake_area_km2:0.11, lake_growth_pct_yr:45, dam_type:2, headwall_slope_deg:55,
       glacier_area_km2:4.6, precip_anomaly_pct:-30, temp_anomaly_c:2.0, downstream_exposure:0.88 },
  mlNotes:{ lake_area_km2:'V — 0.11 km² barrier lake (NDRRMA via WFP)',
            lake_growth_pct_yr:'S — proxy only; a blockage is instantaneous, there is no real growth series',
            dam_type:'V — ice/debris dam', headwall_slope_deg:'A — DEM-scale estimate',
            glacier_area_km2:'A — catchment estimate', precip_anomaly_pct:'V — DHM: no heavy rain',
            temp_anomaly_c:'A — regional estimate', downstream_exposure:'A — derived from exposure counts' },

  why:[
    'Ice-rock slab detached from the Langtang Lirung north face and fell ≈1,200 m into the Lhende Khola (ICIMOD)',
    'Channel blockage formed and released — barrier lake of ≈0.11 km² later breached on 28 Aug (NDRRMA)',
    'Trishuli rose ≈9 m in 30 minutes at Galchhi, 88 km downstream — almost no warning time',
    'Dense border infrastructure (dry port, truck park, hydropower) sits on the first flat riverbed at Rasuwagadhi',
    'Rainfall was ruled out by DHM, so no rainfall-based warning would have been triggered',
  ],

  impact:{ hazard:'Ice-Rock Avalanche → Debris Flood', severity:'HIGH',
           area:'≈40 km road corridor damaged', exposure:'62 districts reported missing persons',
           safeZone:'Dhunche (1,960 m, district HQ)' },

  rescue:{
    startLabel:'Forward Rescue Base — Syabrubesi',
    zoneLabel:'Timure / Rasuwagadhi — border settlement & dry port',
    destLabel:'Dhunche — district HQ relief hub (1,960 m)',
    priorities:[
      ['Priority 1','Timure Bazaar & Rasuwagadhi dry port — swept away'],
      ['Priority 2','Haku Besi & Mailung — Upper Trishuli 3A worksite'],
      ['Priority 3','Syabrubesi bazaar & Langtang trek trailhead'],
    ],
    hospital:'Rasuwa District Hospital, Dhunche', hospitalDist:'≈18 km from forward base',
    shelter:'Syabrubesi Relief Camp', shelterDist:'≈1 km from forward base',
    base:'Syabrubesi Forward Base', roadAcc:'Blocked', roadAccPill:'pill-red',
    blockedCorridor:'Pasang Lhamu Highway (H07), Mailung–Haku section',
  },

  gis:{
    center:[28.200, 85.340], zoom:11,
    baseLL:[28.1625, 85.3336], zoneLL:[28.2665, 85.3740], destLL:[28.1119, 85.2969],
    hospLL:[28.1105, 85.2955], shelLL:[28.1660, 85.3355],
    basePop:'<b>Forward Rescue Base — Syabrubesi</b><span class="pop-tag">Helipad &amp; staging area · indicative</span>',
    zonePop:'<b>Timure / Rasuwagadhi</b><span class="pop-tag">Worst-hit border settlement · dry port destroyed</span>',
    destPop:'<b>Dhunche — District HQ</b><span class="pop-tag">Relief hub, 1,960 m, above the valley floor</span>',
    hospPop:'<b>Rasuwa District Hospital, Dhunche</b><span class="pop-tag">Nearest district hospital · approximate location</span>',
    shelPop:'<b>Syabrubesi Relief Camp</b><span class="pop-tag">Indicative shelter site</span>',
    bridges:[
      {ll:[28.2774,85.3777], pop:'<b>Rasuwagadhi Friendship Bridge</b><span class="pop-tag">Nepal–China crossing · destroyed (also lost July 2025)</span>'},
      {ll:[28.2560,85.3715], pop:'<b>Timure Bhotekoshi Bridge</b><span class="pop-tag">On the valley-floor route · destroyed</span>'},
      {ll:[28.2050,85.3520], pop:'<b>Ghattekhola crossing</b><span class="pop-tag">High-risk crossing — status indicative</span>'},
    ],
    blocked:[{ll:[28.2100,85.3540], pop:'<b>Blocked Section — valley-floor road</b><span class="pop-tag">Debris and washed-out carriageway · indicative</span>'}],
    routeA:[[28.1625,85.3336],[28.1830,85.3390],[28.2050,85.3520],[28.2290,85.3620],[28.2665,85.3740],[28.2290,85.3620],[28.2050,85.3520],[28.1625,85.3336],[28.1400,85.3150],[28.1119,85.2969]],
    routeB:[[28.1625,85.3336],[28.1880,85.3430],[28.2150,85.3560],[28.2400,85.3640],[28.2665,85.3740],[28.2200,85.3560],[28.1750,85.3200],[28.1400,85.3040],[28.1119,85.2969]],
    routeC:[[28.1625,85.3336],[28.1900,85.3450],[28.2100,85.3540],[28.2400,85.3650],[28.2665,85.3740]],
    roadNet:[
      [[28.1119,85.2969],[28.1400,85.3150],[28.1625,85.3336],[28.2050,85.3520],[28.2555,85.3702],[28.2774,85.3777]],
      [[28.1119,85.2969],[28.0600,85.2700],[28.0100,85.2200],[27.9600,85.1830],[27.9200,85.1450]],
      [[28.1625,85.3336],[28.1750,85.3200],[28.1580,85.3050],[28.1350,85.2990]],
    ],
    flood:[[28.2820,85.3820],[28.2700,85.3760],[28.2500,85.3690],[28.2200,85.3580],[28.1900,85.3440],[28.1600,85.3300],[28.1550,85.3350],[28.1880,85.3500],[28.2180,85.3650],[28.2520,85.3760],[28.2790,85.3880]],
    floodPop:'<b>Debris-flood corridor — Lhende Khola → Bhotekoshi</b><span class="pop-tag">Approximate extent, redrawn from published ICIMOD/NDRRMA maps</span>',
    landslide:[[28.2200,85.3480],[28.2180,85.3620],[28.1950,85.3600],[28.1960,85.3460]],
    landslidePop:'<b>Slope-failure / debris section</b><span class="pop-tag">Mailung–Haku corridor · approximate</span>',
    routeStats:{
      0:{A:{dist:'26.4 km',time:'71 min',bridges:2,risk:'High Risk',status:'Passable'}, B:{dist:'31.8 km',time:'82 min'}, C:{dist:'14.6 km',blocked:0,status:'Passable'}},
      1:{A:{dist:'26.4 km',time:'96 min',bridges:3,risk:'High Risk',status:'Partial'},  B:{dist:'31.8 km',time:'88 min'}, C:{dist:'14.6 km',blocked:1,status:'Unsafe'}},
      2:{A:{dist:'26.4 km',time:'—',    bridges:3,risk:'Extreme Risk',status:'Severed'}, B:{dist:'31.8 km',time:'104 min'},C:{dist:'14.6 km',blocked:2,status:'Impassable'}},
    },
    routeBReason:'Route B follows the higher Thulo Syabru ridge line instead of the Bhotekoshi valley floor, avoids the destroyed Timure and Rasuwagadhi river crossings, and ends at Dhunche (1,960 m) above the flood corridor. Alignment is indicative — drawn on the mapped road/trail network, not from a documented evacuation order.',
    coordSeed:'lat 28.200, lng 85.340',
  },

  team:{
    baseLabel:'SYABRUBESI BASE', areaLabel:'Zone Density Map — Rasuwa / Bhotekoshi Corridor',
    base:[28.1625,85.3336],
    zones:[
      {id:'Z-01', name:'Timure Bazaar',          ll:[28.2555,85.3702], base:34, risk:'crit', km:12.4, access:'Blocked (1 route)', shelter:'Dhunche Relief Hub'},
      {id:'Z-02', name:'Rasuwagadhi Dry Port',   ll:[28.2774,85.3777], base:26, risk:'crit', km:14.8, access:'Blocked (1 route)', shelter:'Dhunche Relief Hub'},
      {id:'Z-03', name:'Haku Besi',              ll:[28.1180,85.3450], base:18, risk:'crit', km:8.1,  access:'Partial',           shelter:'Syabrubesi Relief Camp'},
      {id:'Z-04', name:'Syabrubesi Bazaar',      ll:[28.1625,85.3336], base:41, risk:'high', km:1.2,  access:'Open',              shelter:'Syabrubesi Relief Camp'},
      {id:'Z-05', name:'Upper Trishuli 3A site', ll:[28.0200,85.2000], base:14, risk:'crit', km:21.5, access:'Partial',           shelter:'Dhunche Relief Hub'},
      {id:'Z-06', name:'Dhunche (District HQ)',  ll:[28.1119,85.2969], base:9,  risk:'mod',  km:18.0, access:'Open',              shelter:'Dhunche Relief Hub'},
    ],
  },

  alert:{
    eventType:'GLOF / Flash Flood', eventTypeReal:'Ice-rock avalanche → debris flood',
    location:'Lhende Khola → Bhotekoshi → Trishuli corridor, Rasuwa',
    action:'Move immediately off the Bhotekoshi/Trishuli valley floor to ground above Dhunche level',
    actionShort:'Leave the river valley floor — move uphill now',
    head:'🚨 HIGH RISK ALERT — HISTORICAL REPLAY',
    zone:'Rasuwa District, Nepal', time:'26 Aug 2026, 08:37 NPT',
    source:'Reconstructed from ICIMOD / NDRRMA / DHM public reporting',
    relayEvent:'Debris flood (ice-rock avalanche)', relayZone:'Bhotekoshi–Trishuli corridor',
    relayTime:'08:37 NPT', relayAction:'Move uphill, off the valley floor', relayExpiry:'30 min',
  },

  report:{
    hazardType:'Ice-rock avalanche → debris flood',
    detectionTime:'26 Aug 2026, 08:37 NPT (event onset — not a prediction)',
    obsSource:'ICIMOD satellite/field reconstruction · USGS seismic · DHM gauges · NDRRMA SitReps',
    area:'≈40 km road corridor; damage traced ≥100 km downstream',
    evidence:'Satellite imagery, video, M5.2 landslide seismic signal, gauge records',
    action:'Evacuate valley floor toward Dhunche (1,960 m)',
    route:'Route B — Thulo Syabru ridge line (indicative)',
  },

  notifications:[
    ['🚨','Ice-rock avalanche','Slab detached from Langtang Lirung north face','risk'],
    ['⚠️','Debris flood','Trishuli rose ≈9 m in 30 min at Galchhi','map'],
    ['ℹ️','Barrier lake','≈0.11 km² lake formed upstream; breached 28 Aug','monitoring'],
    ['✅','Access note','Valley-floor road severed; ridge route indicative','rescue'],
  ],

  demo:[
    'Satellite & seismic observation loaded (26 Aug 2026)',
    'Ice-rock detachment identified on Langtang Lirung',
    'Risk classified HIGH from documented features',
    'Debris-flood corridor drawn from published extent maps',
    'Ridge route away from the Bhotekoshi valley floor',
    'Rescue team view — Timure, Rasuwagadhi, Haku Besi',
    'Alert text — what a warning should have said',
    'Alert relayed to a second demo device',
    'Dashboard updates with NDRRMA-reported figures',
  ],

  sources:[
    {n:'ICIMOD — Kyirong–Rasuwa Flood 2026', u:'https://www.icimod.org/kyirong-rasuwa-flood-2026-nepal-china-border/', d:'2026-09-20'},
    {n:'ICIMOD press release — major flash flood, Rasuwa', u:'https://www.icimod.org/press-release/major-flash-flood-sweeps-through-nepals-rasuwa-district-raising-fears-of-further-downstream-flooding/', d:'2026-09-20'},
    {n:'NDRRMA — Rasuwa/Bhotekoshi SitRep #01 (1 Sep 2026)', u:'https://ndrrma.gov.np/mediafiles/rasuwa/Rasuwa_Flood_SitRep_Temp_ENG_01_01092026.pdf', d:'2026-09-01'},
    {n:'ICIMOD & partners — August 2026 Nepal Trishuli Flood story map', u:'https://storymaps.arcgis.com/stories/f2b2425eac544929a7d18f4c90b41d66', d:'2026-09-20'},
    {n:'Severe-weather.eu — USGS landslide reclassification (M4.4 → M5.2)', u:'https://www.severe-weather.eu/global-weather/nepal-tibet-flood-ice-rock-avalanche-usgs-landslide-august-2026-rrc/', d:'2026-09-20'},
    {n:'ADRC compilation of NDRRMA / WFP / OCHA situation reports', u:'https://www.adrc.asia/publications/disaster_report/pdf/2026/ADRC_FL_NPL_Rasuwa_20260826_EN.pdf', d:'2026-09-20'},
    {n:'Wikipedia — 2026 Nepal floods (index to primary sources; NEA figures)', u:'https://en.wikipedia.org/wiki/2026_Nepal_floods', d:'2026-09-20'},
    {n:'Down To Earth — ICIMOD probe into the ice-rock avalanche trigger', u:'https://www.downtoearth.org.in/natural-disasters/did-an-ice-rock-avalanche-originating-from-a-high-altitude-area-trigger-the-trishuli-flash-flood', d:'2026-09-20'},
  ],

  quality:[
    ['Event mechanism, timing, fall height','V','ICIMOD'],
    ['USGS M5.2 landslide-source reclassification','V','USGS via severe-weather.eu'],
    ['Barrier lake 0.11 km², breach on 28 Aug','V','NDRRMA via WFP / CARE-ICIMOD'],
    ['9 m rise in 30 min at Galchhi; 8.5 m gauge; 57.4 M m³ at Devghat','V','DHM / NDRRMA via story map'],
    ['Deaths 1,410 · missing 6,145 (Nepal); 43 dead, 519 missing (Tibet AR)','V','as reported, NDRRMA / Nepal Police, retrieved 20 Sep 2026 — still changing'],
    ['≈40 km roads, >80 bridges, ≥14 energy facilities; 13 HPPs, ≈431 MW','V','WFP SitRep / Nepal Electricity Authority'],
    ['Rasuwagadhi 28.2774,85.3777 · Timure 28.2555,85.3702 · Galchhi 27.7961,85.0003','V','story map'],
    ['Syabrubesi, Dhunche, hospital, shelter, Haku Besi, Trishuli 3A coordinates','A','gazetteer-level, not surveyed'],
    ['Headwall slope 55°, glacier area 4.6 km², temp anomaly +2.0 °C','A','order-of-magnitude estimates'],
    ['Flood & landslide polygons','A','redrawn by eye from published extent maps'],
    ['Routes A / B / C alignments, distances, times, bridge counts','A','indicative — drawn on the mapped road network; not documented evacuation routes'],
    ['Per-zone people counts in the Rescue Team view','S','SIMULATED — no verified live crowd sensing existed'],
    ['River-level slider states, "Active Alerts 09" as a live count','S','UI demonstration only'],
  ],
},

/* ============================================================== KEDARNATH */
in2013: {
  id:'in2013', short:'India · Kedarnath 2013',
  title:'Kedarnath Disaster — Extreme Rainfall & Chorabari Lake Breach',
  country:'India', hazard:'Extreme rainfall → moraine-dam breach → debris flood',
  hazardShort:'Extreme Rainfall / Moraine-Dam Breach',
  eventTime:'16 Jun 2013, 17:15 IST → 17 Jun 2013, 06:45 IST', eventDate:'16–17 Jun 2013', tz:'IST (UTC+5:30)',
  incidentId:'HKH-IN-2013-001',
  region:'Chorabari Tal → Mandakini valley, Rudraprayag District, Uttarakhand',
  detectedChange:'Chorabari Lake moraine dam breached; lake drained and never reformed',
  changePct:'315 mm rain in 24 h at the WIHG Chorabari camp',
  summary:'Two events, not one. On the evening of 16 June 2013 torrential rain in the Saraswati and Dudh Ganga catchments sent a debris-laden flood through upper Kedarnath and completely destroyed Rambara. At 06:45 IST on 17 June the moraine dam of Chorabari Tal, about 2 km upstream of the temple, gave way and released a second, larger flash flood down the Mandakini through Gaurikund, Sonprayag, Guptkashi and Agastyamuni. The lake did not reform: the moraine was largely washed away. Roughly 300,000 pilgrims were in the region at the peak of the Char Dham season and there was effectively no warning.',

  kpi:{ hazardStatus:'EMERGENCY', zoneFoot:'Rudraprayag District, Uttarakhand',
        areaKm2:{v:'14 km pilgrim route destroyed', s:'V', src:1},
        alerts:{v:'02', s:'V', src:2, foot:'Two separate flood events, 16 & 17 June'} },

  mparams:[
    {icon:'🏔️', label:'Glacier Geometry', status:'anomaly',
     metrics:[['Source Glacier','Chorabari Glacier'],['Cirque Width','≈6 km'],['Glacier Area','≈6.6 km² — approximate'],['Ice Thickness','No ground survey used here']],
     source:'Chorabari Glacier sits in a cirque some 6 km wide with meltwater flowing down a narrow steep-sided valley (Wikipedia/Chorabari Lake, citing Negi) — verified description; area figure approximate.'},
    {icon:'❄️', label:'Ice / Snow', status:'anomaly',
     metrics:[['Snowmelt','Rapid melt of Chorabari Glacier snowpack'],['Contribution','Rain-on-snow amplification'],['Avalanche Input','Reported into the lake (WIHG)'],['Water-level Rise','+7 m before breach']],
     source:'WIHG glaciologist D.P. Dobhal (via Dialogue Earth, "Death of Chorabari lake"): incessant rain and rapid snowmelt raised the lake level by seven metres — verified as reported.'},
    {icon:'🪨', label:'Crack & Instability', status:'high',
     metrics:[['Moraine Dam','Unstable, already under pressure'],['Breach','17 Jun 2013, 06:45 IST'],['Post-event State','Lake gone; boulder-strewn flat remains'],['Bank Erosion','Severe along the Mandakini']],
     source:'Wikipedia/Chorabari Lake and Dialogue Earth: on 17 June 2013 the moraine gave way; the lake did not reform because much of the moraine had been washed away — verified.'},
    {icon:'💧', label:'Glacial Lakes', status:'high',
     metrics:[['Lake','Chorabari Tal (Gandhi Sarovar)'],['Coordinates','30.7475 N, 79.0608 E'],['Distance to Kedarnath','≈2 km upstream'],['Lake Area','≈0.04 km² — approximate'],['Dam Type','Moraine']],
     source:'Coordinates and the ≈2 km upstream position from the Chorabari Lake record — verified. Lake area is an approximate pre-event figure.'},
    {icon:'🌊', label:'Hydrology', status:'high',
     metrics:[['River','Mandakini (Ganga tributary)'],['Event 1','16 Jun, 17:15 IST — Saraswati / Dudh Ganga flood'],['Event 2','17 Jun, 06:45 IST — Chorabari breach'],['Sediment Load','Very high; boulder-laden'],['Settlements Hit','Kedarnath, Rambara, Gaurikund, Sonprayag, Agastyamuni']],
     source:'Shri Kedarnath Charitable Trust (Uttarakhand Govt.) chronology of the two events with times — verified.'},
    {icon:'☁️', label:'Weather / Climate', status:'high',
     metrics:[['Rainfall, Chorabari camp (3,800 m)','325 mm over 16–17 Jun'],['24-hour Rainfall','315 mm at the WIHG camp'],['Dokriani camp (2,500 m)','269 mm over 16–17 Jun'],['Driver','Monsoon meeting a westerly disturbance'],['Anomaly','Extreme for this altitude']],
     source:'Mehta et al. via ResearchGate for the camp totals; Dialogue Earth for the 315 mm/24 h WIHG record — verified as published.'},
    {icon:'⛰️', label:'Terrain', status:'high',
     metrics:[['Headwall Slope','≈45° — approximate'],['Valley Form','Narrow, steep-sided'],['Channel Constriction','Upstream of Gaurikund'],['Landslide Susceptibility','Very high']],
     source:'Published analyses attribute much of the Gaurikund destruction to narrowing of the river course slightly upstream — verified narrative; slope value approximate.'},
    {icon:'🌉', label:'Infrastructure', status:'high',
     metrics:[['Pilgrim Route Destroyed','14 km, Gaurikund → Kedarnath'],['Rambara','Completely washed away'],['Bridges & Roads','≈US$285 million damage (Kala)'],['Dam Projects','≈US$30 million damage'],['Tourism Loss','≈US$195 million']],
     source:'Route length from Dialogue Earth/PreventionWeb; damage costs as compiled by ecologist C.P. Kala — verified as reported, converted figures.'},
    {icon:'🏘️', label:'Exposure', status:'high',
     metrics:[['Death Toll','6,054 (official, later figure)'],['Presumed Dead','>5,700, incl. 934 local residents'],['Pilgrims Stranded','≈300,000 — approximate'],['Season','Peak Char Dham pilgrimage'],['People Affected (region)','Millions across Uttarakhand']],
     source:'Government of Uttarakhand figures as reported: >5,700 presumed dead including 934 local residents, toll later placed at 6,054 — verified as reported. The ≈300,000 stranded figure is widely cited but approximate.'},
    {icon:'🚑', label:'Response Resources', status:'anomaly',
     metrics:[['Air Rescue','IAF/ITBP/NDRF, helipads at Guptkashi & Gauchar'],['Road Head','Sonprayag — road destroyed beyond'],['Nearest Hospital','District Hospital, Rudraprayag'],['Warning Issued','None effective in time'],['Access','Severed for days']],
     source:'Reconstructed from published accounts of the response. Specific base and helipad locations are approximate; there was, as reported, effectively no warning and most people were taken by surprise.'},
  ],

  ml:{ lake_area_km2:0.04, lake_growth_pct_yr:40, dam_type:1, headwall_slope_deg:45,
       glacier_area_km2:6.6, precip_anomaly_pct:375, temp_anomaly_c:1.5, downstream_exposure:0.95 },
  mlNotes:{ lake_area_km2:'A — pre-event estimate', lake_growth_pct_yr:'A — proxy for the +7 m level rise',
            dam_type:'V — moraine', headwall_slope_deg:'A', glacier_area_km2:'A',
            precip_anomaly_pct:'V — 315–325 mm vs seasonal baseline', temp_anomaly_c:'A',
            downstream_exposure:'A — derived from the pilgrim load' },

  why:[
    '315 mm of rain in 24 hours at 3,800 m — extreme for that altitude (WIHG camp record)',
    'Chorabari Tal water level rose ≈7 m against an already weakened moraine dam',
    'Two floods in 14 hours: the 16 June rainfall flood, then the 17 June moraine breach',
    'The lake sat only ≈2 km upstream of Kedarnath — travel time measured in minutes',
    '≈300,000 pilgrims were in a narrow valley at peak season with no effective warning',
  ],

  impact:{ hazard:'Extreme Rainfall → Moraine Breach', severity:'EMERGENCY',
           area:'14 km pilgrim route destroyed; Mandakini valley to Rudraprayag',
           exposure:'≈300,000 pilgrims in the region (approximate)',
           safeZone:'Guptkashi (1,319 m) — relief and helipad hub' },

  rescue:{
    startLabel:'Rescue Staging — Sonprayag road head',
    zoneLabel:'Kedarnath town & temple precinct',
    destLabel:'Guptkashi — relief camp & helipad',
    priorities:[
      ['Priority 1','Kedarnath temple precinct — thousands sheltering'],
      ['Priority 2','Rambara & Jungle Chatti — route completely destroyed'],
      ['Priority 3','Gaurikund & Sonprayag — road head cut off'],
    ],
    hospital:'District Hospital, Rudraprayag', hospitalDist:'≈40 km from staging point',
    shelter:'Guptkashi Relief Camp', shelterDist:'≈13 km from staging point',
    base:'Sonprayag Staging Point', roadAcc:'Blocked', roadAccPill:'pill-red',
    blockedCorridor:'Sonprayag–Gaurikund road & the Gaurikund–Kedarnath foot route',
  },

  gis:{
    center:[30.660, 79.030], zoom:11,
    baseLL:[30.6250, 78.9900], zoneLL:[30.7352, 79.0669], destLL:[30.5290, 79.0530],
    hospLL:[30.5300, 79.0520], shelLL:[30.6300, 78.9950],
    basePop:'<b>Sonprayag — rescue staging / road head</b><span class="pop-tag">Approximate location · indicative role</span>',
    zonePop:'<b>Kedarnath town &amp; temple</b><span class="pop-tag">Upper town destroyed; temple survived</span>',
    destPop:'<b>Guptkashi — relief camp &amp; helipad</b><span class="pop-tag">Air-rescue hub, 1,319 m</span>',
    hospPop:'<b>Community Health Centre, Guptkashi</b><span class="pop-tag">Nearest functioning facility · approximate</span>',
    shelPop:'<b>Sonprayag relief camp</b><span class="pop-tag">Indicative shelter site</span>',
    bridges:[
      {ll:[30.6494,79.0263], pop:'<b>Gaurikund crossing</b><span class="pop-tag">Mandakini crossing · destroyed</span>'},
      {ll:[30.6900,79.0600], pop:'<b>Rambara bridge</b><span class="pop-tag">Rambara completely washed away, 16 Jun</span>'},
    ],
    blocked:[{ll:[30.6430,79.0180], pop:'<b>Blocked Section — Sonprayag–Gaurikund road</b><span class="pop-tag">Carriageway washed out · indicative</span>'}],
    routeA:[[30.6250,78.9900],[30.6380,79.0110],[30.6494,79.0263],[30.6900,79.0600],[30.7150,79.0640],[30.7352,79.0669],[30.7150,79.0640],[30.6900,79.0600],[30.6494,79.0263],[30.6250,78.9900],[30.5900,78.9950],[30.5290,79.0530]],
    routeB:[[30.6250,78.9900],[30.6480,79.0250],[30.6900,79.0580],[30.7352,79.0669],[30.6850,79.0900],[30.6400,79.1050],[30.5800,79.1000],[30.5450,79.0900],[30.5290,79.0530]],
    routeC:[[30.6250,78.9900],[30.6350,79.0050],[30.6430,79.0180],[30.6900,79.0600],[30.7352,79.0669]],
    roadNet:[
      [[30.5290,79.0530],[30.5700,79.0200],[30.6000,78.9950],[30.6250,78.9900],[30.6494,79.0263]],
      [[30.5290,79.0530],[30.4600,79.0350],[30.3900,79.0200],[30.3300,78.9600],[30.2840,78.9810]],
      [[30.5450,79.0900],[30.5800,79.1000],[30.6400,79.1050],[30.6850,79.0900]],
    ],
    flood:[[30.7480,79.0620],[30.7360,79.0700],[30.7150,79.0670],[30.6900,79.0620],[30.6600,79.0400],[30.6300,79.0000],[30.6200,78.9860],[30.6280,78.9840],[30.6420,79.0060],[30.6720,79.0480],[30.7000,79.0640],[30.7300,79.0740],[30.7500,79.0680]],
    floodPop:'<b>Mandakini debris-flood corridor</b><span class="pop-tag">Approximate extent, redrawn from published post-event maps</span>',
    landslide:[[30.6800,79.0520],[30.6790,79.0680],[30.6520,79.0620],[30.6540,79.0460]],
    landslidePop:'<b>Slope failure / bank erosion section</b><span class="pop-tag">Rambara reach · approximate</span>',
    routeStats:{
      0:{A:{dist:'32.1 km',time:'8 h 30 (mixed foot/road)',bridges:2,risk:'High Risk',status:'Passable'}, B:{dist:'38.4 km',time:'11 h 00'}, C:{dist:'16.8 km',blocked:0,status:'Passable'}},
      1:{A:{dist:'32.1 km',time:'11 h 00',bridges:2,risk:'High Risk',status:'Partial'},                  B:{dist:'38.4 km',time:'12 h 00'}, C:{dist:'16.8 km',blocked:1,status:'Unsafe'}},
      2:{A:{dist:'32.1 km',time:'—',      bridges:2,risk:'Extreme Risk',status:'Severed'},               B:{dist:'38.4 km',time:'14 h 00'}, C:{dist:'16.8 km',blocked:2,status:'Impassable'}},
    },
    routeBReason:'Route B leaves the Mandakini gorge and uses the Chaumasi–Kalimath alignment to reach Guptkashi — the alternate approach that was actually used after the main route was destroyed. It avoids the Rambara and Gaurikund crossings. Alignment is indicative and approximate.',
    coordSeed:'lat 30.660, lng 79.030',
  },

  team:{
    baseLabel:'SONPRAYAG STAGING', areaLabel:'Zone Density Map — Mandakini / Kedarnath Valley',
    base:[30.6250,78.9900],
    zones:[
      {id:'Z-01', name:'Kedarnath temple precinct', ll:[30.7352,79.0669], base:52, risk:'crit', km:19.2, access:'Blocked (1 route)', shelter:'Guptkashi Relief Camp'},
      {id:'Z-02', name:'Rambara',                   ll:[30.6900,79.0600], base:28, risk:'crit', km:12.6, access:'Blocked (1 route)', shelter:'Guptkashi Relief Camp'},
      {id:'Z-03', name:'Jungle Chatti',             ll:[30.6700,79.0450], base:16, risk:'crit', km:9.4,  access:'Blocked (1 route)', shelter:'Sonprayag Relief Camp'},
      {id:'Z-04', name:'Gaurikund',                 ll:[30.6494,79.0263], base:38, risk:'crit', km:5.8,  access:'Partial',           shelter:'Sonprayag Relief Camp'},
      {id:'Z-05', name:'Sonprayag road head',       ll:[30.6250,78.9900], base:24, risk:'high', km:0.5,  access:'Open',              shelter:'Sonprayag Relief Camp'},
      {id:'Z-06', name:'Guptkashi helipad',         ll:[30.5290,79.0530], base:11, risk:'mod',  km:13.1, access:'Open',              shelter:'Guptkashi Relief Camp'},
    ],
  },

  alert:{
    eventType:'GLOF / Flash Flood', eventTypeReal:'Extreme rainfall + moraine-dam breach',
    location:'Chorabari Tal → Mandakini valley, Rudraprayag District',
    action:'Leave the Mandakini channel and the Gaurikund–Kedarnath route; climb to high ground immediately',
    actionShort:'Leave the river route — climb to high ground now',
    head:'🚨 EMERGENCY ALERT — HISTORICAL REPLAY',
    zone:'Kedarnath valley, Uttarakhand', time:'17 Jun 2013, 06:45 IST',
    source:'Reconstructed from WIHG / NIDM / Uttarakhand Govt. public reporting',
    relayEvent:'Moraine-dam breach flood', relayZone:'Mandakini valley',
    relayTime:'06:45 IST', relayAction:'Climb away from the river route', relayExpiry:'20 min',
  },

  report:{
    hazardType:'Extreme rainfall → moraine-dam breach → debris flood',
    detectionTime:'16 Jun 2013 17:15 IST and 17 Jun 2013 06:45 IST (event onsets — not predictions)',
    obsSource:'WIHG Chorabari camp records · Uttarakhand Govt. chronology · ISRO-NRSC / NIDM post-event studies',
    area:'14 km pilgrim route destroyed; Mandakini valley to Rudraprayag',
    evidence:'Rain-gauge records, post-event satellite imagery, field surveys',
    action:'Evacuate the Mandakini channel toward Guptkashi',
    route:'Route B — Chaumasi / Kalimath alignment (indicative)',
  },

  notifications:[
    ['🚨','Extreme rainfall','315 mm in 24 h at the Chorabari camp (3,800 m)','risk'],
    ['⚠️','Moraine breach','Chorabari Tal dam gave way, 17 Jun 06:45 IST','map'],
    ['ℹ️','Lake lost','Chorabari Tal never reformed — moraine washed away','monitoring'],
    ['✅','Access note','Gaurikund–Kedarnath route destroyed; alternate indicative','rescue'],
  ],

  demo:[
    'Rain-gauge & satellite records loaded (16–17 Jun 2013)',
    'Chorabari Tal moraine breach identified',
    'Risk classified EMERGENCY from documented features',
    'Mandakini flood corridor drawn from published maps',
    'Alternate route away from the destroyed pilgrim track',
    'Rescue team view — Kedarnath, Rambara, Gaurikund',
    'Alert text — what a warning should have said',
    'Alert relayed to a second demo device',
    'Dashboard updates with officially reported figures',
  ],

  sources:[
    {n:'Chorabari Lake — coordinates, breach, post-event state', u:'https://en.wikipedia.org/wiki/Chorabari_Lake', d:'2026-09-20'},
    {n:'Dialogue Earth — Kedarnath: a decade after the floods', u:'https://dialogue.earth/en/climate/a-decade-after-the-floods-is-kedarnath-safer/', d:'2026-09-20'},
    {n:'Shri Kedarnath Charitable Trust (Uttarakhand Govt.) — Natural Calamities 2013 chronology', u:'https://shrikedarnathcharitabletrust.uk.gov.in/Naturalcalamities2013', d:'2026-09-20'},
    {n:'Dialogue Earth — Death of Chorabari lake (WIHG 315 mm / +7 m)', u:'https://dialogue.earth/en/climate/death-of-chorabari-lake/', d:'2026-09-20'},
    {n:'PreventionWeb — India: a decade after the floods, is Kedarnath safer?', u:'https://www.preventionweb.net/news/decade-after-floods-kedarnath-safer', d:'2026-09-20'},
    {n:'Wikipedia — 2013 North India floods (index to primary sources)', u:'https://en.wikipedia.org/wiki/2013_North_India_floods', d:'2026-09-20'},
    {n:'Mehta et al., camp rainfall totals (via ResearchGate figure record)', u:'https://www.researchgate.net/figure/ew-of-the-Kedarnath-township-ravaged-by-the-flood-of-June-2013-with-camera-looking-south_fig2_259934156', d:'2026-09-20'},
  ],

  quality:[
    ['Two-event chronology with times (16 Jun 17:15, 17 Jun 06:45)','V','Uttarakhand Govt. / Shri Kedarnath Charitable Trust'],
    ['Chorabari Lake 30.7475 N, 79.0608 E; ≈2 km upstream; did not reform','V','Chorabari Lake record'],
    ['315 mm in 24 h (WIHG camp); 325 mm over 16–17 Jun at 3,800 m; 269 mm at Dokriani','V','Dialogue Earth / Mehta et al.'],
    ['Lake level rise ≈7 m before breach','V','WIHG (D.P. Dobhal) via Dialogue Earth'],
    ['Death toll 6,054; >5,700 presumed dead incl. 934 residents','V','Government of Uttarakhand, as reported'],
    ['14 km pilgrim route destroyed; Rambara washed away','V','Dialogue Earth / Uttarakhand Govt.'],
    ['Damage US$285 M roads/bridges, $30 M dams, $195 M tourism','V','C.P. Kala, as reported'],
    ['≈300,000 pilgrims stranded','A','widely cited, not from a single primary count'],
    ['Kedarnath, Rambara, Gaurikund, Sonprayag, Guptkashi, Rudraprayag coordinates','A','gazetteer-level'],
    ['Glacier area 6.6 km², lake area 0.04 km², slope 45°, temp anomaly +1.5 °C','A','order-of-magnitude estimates'],
    ['Flood & landslide polygons','A','redrawn by eye from published post-event maps'],
    ['Routes A / B / C alignments, distances, times','A','indicative; Route B follows the Chaumasi–Kalimath alternate'],
    ['Per-zone people counts in the Rescue Team view','S','SIMULATED — no crowd sensing existed in 2013'],
    ['River-level slider states','S','UI demonstration only'],
  ],
},

/* ================================================================= SIKKIM */
in2023: {
  id:'in2023', short:'India · Sikkim 2023',
  title:'South Lhonak GLOF — Teesta III Dam Failure',
  country:'India', hazard:'Moraine collapse → GLOF → dam failure → multihazard cascade',
  hazardShort:'GLOF / Dam Failure Cascade',
  eventTime:'3 Oct 2023 (late) → 4 Oct 2023, ≈00:30 IST', eventDate:'3–4 Oct 2023', tz:'IST (UTC+5:30)',
  incidentId:'HKH-IN-2023-001',
  region:'South Lhonak Lake → Teesta River, Mangan & Pakyong Districts, Sikkim',
  detectedChange:'Frozen lateral moraine collapsed into South Lhonak Lake; terminal moraine breached',
  changePct:'≈50 million m³ of lake water drained',
  summary:'On 3 October 2023 about 14.7 million m³ of frozen lateral moraine collapsed into South Lhonak Lake at 5,200 m. The impact generated an approximately 20 m tsunami-like wave, breached the terminal moraine and drained around 50 million m³ of water. The flood eroded roughly 270 million m³ of sediment on its way down and reached the 1,200 MW Teesta III dam at Chungthang at about 00:30 IST on 4 October, before the gates could be opened; the 60 m dam was destroyed in minutes, adding its stored water to the flood. The surge travelled 385 km down the Teesta into Bangladesh.',

  kpi:{ hazardStatus:'EMERGENCY', zoneFoot:'Mangan & Pakyong Districts, Sikkim',
        areaKm2:{v:'385 km flow path', s:'V', src:1},
        alerts:{v:'04', s:'V', src:3, foot:'Relief camps in four affected districts'} },

  mparams:[
    {icon:'🏔️', label:'Glacier Geometry', status:'high',
     metrics:[['Source Glacier','South Lhonak Glacier'],['Retreat','≈2 km between 1962 and 2008'],['Further Retreat','≈400 m, 2008–2019'],['Glacier Area','≈6.9 km² — approximate']],
     source:'Raj et al. via the Geosystems and Geoenvironment review: the glacier retreated ≈2 km over 46 years and a further ≈400 m from 2008 to 2019 — verified as published. Area figure approximate.'},
    {icon:'❄️', label:'Ice / Snow', status:'high',
     metrics:[['Moraine Collapse Volume','14.7 million m³ (frozen lateral moraine)'],['Alternative Estimate','≈38.31 million m³ debris (Mohanty et al.)'],['Glacier Calving','≈7 million m³ ice mass lost'],['Permafrost Role','Degradation implicated']],
     source:'Science (2025) multihazard-cascade paper for 14.7 million m³; Scientific Reports (Mohanty et al.) for the ≈38.31 million m³ debris and ≈7 million m³ calving estimates — both verified as published; the estimates differ between studies.'},
    {icon:'🪨', label:'Crack & Instability', status:'high',
     metrics:[['Impact Wave','≈20 m, tsunami-like'],['Terminal Moraine','Breached'],['Downstream Erosion','≈270 million m³ of sediment'],['Peak Height 1 km Downstream','≈11 m']],
     source:'Science (2025) for the ≈20 m impact wave and ≈270 million m³ erosion; Sattar et al. (2025) modelling via Petley\'s Landslide Blog for the ≈11 m peak 1 km downstream — verified as published.'},
    {icon:'💧', label:'Glacial Lakes', status:'high',
     metrics:[['Lake','South Lhonak Lake'],['Elevation','5,200 m a.s.l.'],['Pre-event Area','≈1.68 km² — approximate'],['Water Drained','≈50 million m³'],['Dam Type','Moraine'],['Residual Water','Lake not fully emptied']],
     source:'Science (2025) for the ≈50 million m³ drained and the 5,200 m elevation — verified. Pre-event area is an approximate inventory-scale figure; imagery shows water remaining after the GLOF.'},
    {icon:'🌊', label:'Hydrology', status:'high',
     metrics:[['River','Teesta (Brahmaputra tributary)'],['Distance to Teesta III Dam','≈60–68 km (studies differ)'],['Arrival at Chungthang','≈00:30 IST, 4 Oct 2023'],['Downstream Rise','15–20 ft (≈4.6–6.1 m)'],['Total Flow Path','385 km to Bangladesh']],
     source:'Petley\'s Landslide Blog / Eos for the 00:30 arrival; Science (2025) for the 385 km path; Scientific Reports and Wikipedia for the 15–20 ft downstream rise — verified as published. Distance to the dam is quoted as ≈60, 65 or 68 km in different studies.'},
    {icon:'☁️', label:'Weather / Climate', status:'anomaly',
     metrics:[['Antecedent Rainfall','>200 mm reported in preceding hours'],['Role','Destabilising, not sole trigger'],['Cloudburst Hypothesis','Proposed in some studies'],['Temperature Anomaly','+2.5 °C — approximate']],
     source:'Intense antecedent rainfall exceeding 200 mm is reported as having destabilised the moraine slope; a cloudburst contribution is proposed in the Geosystems and Geoenvironment study. Studies disagree on how much rainfall mattered. Temperature anomaly is approximate.'},
    {icon:'⛰️', label:'Terrain', status:'high',
     metrics:[['Headwall Slope','≈45° — approximate'],['Valley Form','Narrow Teesta gorge'],['Erodible Channel','Very high sediment availability'],['Landslide Susceptibility','Very high']],
     source:'Science (2025) attributes severity partly to the massive amount of eroded material and the narrow valley with recent construction — verified narrative; slope value approximate.'},
    {icon:'🌉', label:'Infrastructure', status:'high',
     metrics:[['Teesta III Dam','1,200 MW, 60 m high — destroyed'],['Stored Water Released','≈5.08 million m³'],['Bridges Destroyed','13 (Mohanty et al.) / 16 (Govt. of Sikkim)'],['Residences Destroyed','≈1,200'],['Road','NH-10 severely damaged']],
     source:'Eos/Petley for the 60 m dam height; Government of Sikkim (8 Nov 2023) for 16 bridges and the ≈5.08 million m³ release; Scientific Reports for 13 bridges and ≈1,200 residences — verified as reported; counts differ between sources.'},
    {icon:'🏘️', label:'Exposure', status:'high',
     metrics:[['Deaths','55 (Science) / 42–46 (Govt. of Sikkim, earlier)'],['Missing','74–77'],['People Affected','88,400'],['Evacuated','5,665'],['Rescued','2,563'],['Army Personnel','Significant losses at Bardang']],
     source:'Science (2025) reports 55 deaths and 74 missing in Sikkim; the Government of Sikkim reported 42 dead, >77 missing, 88,400 affected, 5,665 evacuated and 2,563 rescued as of 8 Nov 2023 — both verified as reported on their respective dates.'},
    {icon:'🚑', label:'Response Resources', status:'anomaly',
     metrics:[['Relief Camps','4 districts; 4 still open on 8 Nov 2023'],['Responders','Army, ITBP, NDRF, Sikkim SDMA'],['Nearest Hospitals','District Hospital Mangan; STNM Gangtok'],['Access','NH-10 severed; bridges lost'],['Improvised Crossing','Bamboo bridge built at Chungthang']],
     source:'Government of Sikkim relief figures (8 Nov 2023) and contemporaneous reporting (Sikkim Express via Penn State IEE) — verified as reported.'},
  ],

  ml:{ lake_area_km2:1.68, lake_growth_pct_yr:9, dam_type:1, headwall_slope_deg:45,
       glacier_area_km2:6.9, precip_anomaly_pct:210, temp_anomaly_c:2.5, downstream_exposure:0.80 },
  mlNotes:{ lake_area_km2:'A — pre-event inventory-scale estimate', lake_growth_pct_yr:'A — from the documented rapid expansion',
            dam_type:'V — moraine', headwall_slope_deg:'A', glacier_area_km2:'A',
            precip_anomaly_pct:'A — from the >200 mm antecedent rainfall reports',
            temp_anomaly_c:'A', downstream_exposure:'A — derived from affected-population counts' },

  why:[
    'South Lhonak was already the largest and fastest-growing lake in the basin — flagged high-hazard years before',
    '14.7 million m³ of frozen lateral moraine collapsed into the lake and raised an ≈20 m impulse wave',
    '≈50 million m³ drained through the breached terminal moraine',
    'The flood eroded ≈270 million m³ of sediment, multiplying its destructive volume',
    'Teesta III sat ≈60–68 km downstream in a narrow gorge; the surge arrived at ≈00:30 before gates could open',
  ],

  impact:{ hazard:'GLOF → Dam Failure Cascade', severity:'EMERGENCY',
           area:'385 km flow path, Sikkim to Bangladesh',
           exposure:'88,400 people affected (Govt. of Sikkim)',
           safeZone:'Gangtok — state relief and medical hub' },

  rescue:{
    startLabel:'Rescue Base — Mangan (District HQ)',
    zoneLabel:'Chungthang — Teesta III dam site',
    destLabel:'Gangtok — state relief & medical hub',
    priorities:[
      ['Priority 1','Chungthang bazaar & Teesta III dam colony'],
      ['Priority 2','Lachen / Lachung — tourists and residents cut off'],
      ['Priority 3','Dikchu, Singtam & Rangpo — NH-10 corridor'],
    ],
    hospital:'District Hospital, Mangan', hospitalDist:'≈0.5 km from rescue base',
    shelter:'Mangan Relief Camp', shelterDist:'≈0.5 km from rescue base',
    base:'Mangan District Base', roadAcc:'Blocked', roadAccPill:'pill-red',
    blockedCorridor:'NH-10 Teesta corridor & the Sanklang Teesta crossing',
  },

  gis:{
    center:[27.450, 88.570], zoom:10,
    baseLL:[27.5100, 88.5300], zoneLL:[27.6000, 88.6400], destLL:[27.3330, 88.6140],
    hospLL:[27.5140, 88.5320], shelLL:[27.5080, 88.5260],
    basePop:'<b>Mangan — District HQ rescue base</b><span class="pop-tag">Army / ITBP / NDRF staging · approximate</span>',
    zonePop:'<b>Chungthang — Teesta III dam site</b><span class="pop-tag">1,200 MW dam destroyed, ≈00:30 IST 4 Oct 2023</span>',
    destPop:'<b>Gangtok — state relief &amp; medical hub</b><span class="pop-tag">STNM Hospital · approximate location</span>',
    hospPop:'<b>District Hospital, Mangan</b><span class="pop-tag">Nearest district hospital · approximate</span>',
    shelPop:'<b>Mangan Relief Camp</b><span class="pop-tag">Indicative shelter site</span>',
    bridges:[
      {ll:[27.5450,88.5700], pop:'<b>Sanklang Teesta crossing</b><span class="pop-tag">Teesta bridge lost · 13–16 bridges destroyed statewide</span>'},
      {ll:[27.5650,88.6050], pop:'<b>Toong crossing</b><span class="pop-tag">High-risk crossing on the valley road · indicative</span>'},
      {ll:[27.4200,88.5200], pop:'<b>Dikchu bridge</b><span class="pop-tag">NH-10 corridor crossing · indicative</span>'},
    ],
    blocked:[{ll:[27.5450,88.5700], pop:'<b>Blocked Section — Sanklang</b><span class="pop-tag">Crossing lost; route severed · indicative</span>'}],
    routeA:[[27.5100,88.5300],[27.5400,88.5600],[27.5650,88.6050],[27.5850,88.6250],[27.6000,88.6400],[27.5700,88.6100],[27.5100,88.5300],[27.4200,88.5200],[27.3700,88.5600],[27.3330,88.6140]],
    routeB:[[27.5100,88.5300],[27.5300,88.5450],[27.5650,88.6000],[27.5900,88.6300],[27.6000,88.6400],[27.5500,88.5700],[27.4700,88.5750],[27.4200,88.5750],[27.3800,88.5950],[27.3330,88.6140]],
    routeC:[[27.5100,88.5300],[27.5250,88.5420],[27.5450,88.5700],[27.5850,88.6250],[27.6000,88.6400]],
    roadNet:[
      [[27.6000,88.6400],[27.5650,88.6050],[27.5100,88.5300],[27.4200,88.5200],[27.2350,88.5000],[27.1770,88.5300]],
      [[27.5100,88.5300],[27.4700,88.5750],[27.4200,88.5750],[27.3800,88.5950],[27.3330,88.6140]],
      [[27.6000,88.6400],[27.6500,88.5900],[27.7167,88.5500]],
    ],
    flood:[[27.6080,88.6460],[27.5900,88.6300],[27.5600,88.6000],[27.5150,88.5330],[27.4200,88.5180],[27.2350,88.4980],[27.1770,88.5280],[27.1700,88.5380],[27.2380,88.5090],[27.4230,88.5300],[27.5200,88.5420],[27.5680,88.6120],[27.6020,88.6530]],
    floodPop:'<b>Teesta GLOF corridor</b><span class="pop-tag">Approximate extent, redrawn from published NRSC/ISRO and study maps. Downstream West Bengal impact is text-only here.</span>',
    landslide:[[27.5600,88.5900],[27.5580,88.6180],[27.5200,88.6100],[27.5230,88.5820]],
    landslidePop:'<b>Bank collapse / slope-failure reach</b><span class="pop-tag">Chungthang–Mangan section · approximate</span>',
    routeStats:{
      0:{A:{dist:'46.8 km',time:'2 h 10',bridges:2,risk:'High Risk',status:'Passable'}, B:{dist:'54.2 km',time:'2 h 35'}, C:{dist:'13.2 km',blocked:0,status:'Passable'}},
      1:{A:{dist:'46.8 km',time:'3 h 05',bridges:3,risk:'High Risk',status:'Partial'},  B:{dist:'54.2 km',time:'2 h 50'}, C:{dist:'13.2 km',blocked:1,status:'Unsafe'}},
      2:{A:{dist:'46.8 km',time:'—',     bridges:3,risk:'Extreme Risk',status:'Severed'},B:{dist:'54.2 km',time:'3 h 20'}, C:{dist:'13.2 km',blocked:2,status:'Impassable'}},
    },
    routeBReason:'Route B leaves the Teesta gorge at Mangan and uses the Phodong–Kabi ridge alignment (NH-310A) down to Gangtok, avoiding the lost Sanklang and Dikchu crossings and the NH-10 riverside sections. Alignment is indicative — drawn on the mapped road network, not from a documented evacuation order.',
    coordSeed:'lat 27.450, lng 88.570',
  },

  team:{
    baseLabel:'MANGAN BASE', areaLabel:'Zone Density Map — Teesta Valley, Sikkim',
    base:[27.5100,88.5300],
    zones:[
      {id:'Z-01', name:'Chungthang Bazaar',      ll:[27.6000,88.6400], base:36, risk:'crit', km:12.8, access:'Blocked (1 route)', shelter:'Mangan Relief Camp'},
      {id:'Z-02', name:'Teesta III dam colony',  ll:[27.5930,88.6440], base:22, risk:'crit', km:13.4, access:'Blocked (1 route)', shelter:'Mangan Relief Camp'},
      {id:'Z-03', name:'Lachen',                 ll:[27.7167,88.5500], base:19, risk:'crit', km:34.0, access:'Blocked (1 route)', shelter:'Mangan Relief Camp'},
      {id:'Z-04', name:'Mangan (District HQ)',   ll:[27.5100,88.5300], base:31, risk:'high', km:0.6,  access:'Open',              shelter:'Mangan Relief Camp'},
      {id:'Z-05', name:'Dikchu',                 ll:[27.4200,88.5200], base:14, risk:'high', km:11.2, access:'Partial',           shelter:'Gangtok Relief Hub'},
      {id:'Z-06', name:'Singtam',                ll:[27.2350,88.5000], base:27, risk:'crit', km:33.5, access:'Partial',           shelter:'Gangtok Relief Hub'},
    ],
  },

  alert:{
    eventType:'GLOF / Flash Flood', eventTypeReal:'GLOF → dam failure cascade',
    location:'South Lhonak Lake → Teesta River, Sikkim',
    action:'Move off the Teesta banks and NH-10 riverside sections to high ground immediately',
    actionShort:'Leave the Teesta banks — move to high ground now',
    head:'🚨 EMERGENCY ALERT — HISTORICAL REPLAY',
    zone:'Teesta valley, Sikkim', time:'4 Oct 2023, ≈00:30 IST',
    source:'Reconstructed from Science (2025) / Sikkim SDMA / NRSC public reporting',
    relayEvent:'GLOF + dam failure', relayZone:'Teesta valley, Sikkim',
    relayTime:'≈00:30 IST', relayAction:'Leave the river banks, move uphill', relayExpiry:'25 min',
  },

  report:{
    hazardType:'GLOF → dam failure → multihazard cascade',
    detectionTime:'3 Oct 2023 (moraine collapse) → 4 Oct 2023 ≈00:30 IST (dam failure) — event onsets, not predictions',
    obsSource:'Science (2025) cascade reconstruction · Scientific Reports (Mohanty et al.) · NRSC/ISRO imagery · Govt. of Sikkim',
    area:'385 km flow path from the lake to Bangladesh',
    evidence:'Pre/post satellite imagery (SPOT, Pléiades, NRSC), DEM differencing, hydraulic modelling',
    action:'Evacuate the Teesta corridor toward Gangtok',
    route:'Route B — Phodong / Kabi ridge alignment (indicative)',
  },

  notifications:[
    ['🚨','Moraine collapse','14.7 M m³ fell into South Lhonak Lake','risk'],
    ['⚠️','GLOF','≈50 M m³ drained; ≈20 m impulse wave','map'],
    ['ℹ️','Dam failure','Teesta III destroyed at ≈00:30 IST, 4 Oct 2023','monitoring'],
    ['✅','Access note','NH-10 severed; ridge route indicative','rescue'],
  ],

  demo:[
    'Satellite & lake-inventory records loaded (Oct 2023)',
    'Moraine collapse into South Lhonak Lake identified',
    'Risk classified EMERGENCY from documented features',
    'Teesta GLOF corridor drawn from published maps',
    'Ridge route away from the NH-10 riverside sections',
    'Rescue team view — Chungthang, Lachen, Singtam',
    'Alert text — what a warning should have said',
    'Alert relayed to a second demo device',
    'Dashboard updates with officially reported figures',
  ],

  sources:[
    {n:'Science (2025) — The Sikkim flood of October 2023: drivers, causes, impacts', u:'https://www.science.org/doi/10.1126/science.ads2659', d:'2026-09-20'},
    {n:'Scientific Reports (Mohanty et al.) — sequence of events leading to the GLOF', u:'https://www.nature.com/articles/s41598-026-35895-7', d:'2026-09-20'},
    {n:'Petley, Landslide Blog / Eos — the 3–4 October 2023 Sikkim GLOF', u:'https://eos.org/thelandslideblog/sikkim-glof-october-2023', d:'2026-09-20'},
    {n:'Penn State IEE — GLOFs: loss of life and infrastructure (Govt. of Sikkim figures)', u:'https://iee.psu.edu/news/blog/glacier-lake-outburst-floods-loss-life-and-infrastructure', d:'2026-09-20'},
    {n:'Geosystems and Geoenvironment — multiple drivers of the South Lhonak GLOF', u:'https://www.sciencedirect.com/science/article/pii/S2772883825000251', d:'2026-09-20'},
    {n:'Penn State — Govt. of Sikkim relief figures as of 8 Nov 2023 (PDF)', u:'https://ecosystems.psu.edu/research/labs/environmental-policy-goddard-chair-group/glacier-lake-outburst-floods-sikkim-wakeup-call-environmental-policy-goddard-chair-group-blog-oct-2023.pdf', d:'2026-09-20'},
    {n:'Wikipedia — 2023 Sikkim flash floods (index to primary sources)', u:'https://en.wikipedia.org/wiki/2023_Sikkim_flash_floods', d:'2026-09-20'},
  ],

  quality:[
    ['14.7 M m³ moraine collapse; ≈20 m impulse wave; ≈50 M m³ drained; ≈270 M m³ eroded','V','Science (2025)'],
    ['Dam struck ≈00:30 IST 4 Oct 2023; 60 m dam destroyed; ≈11 m peak 1 km downstream','V','Petley / Eos; Sattar et al. (2025)'],
    ['≈38.31 M m³ debris and ≈7 M m³ calving (alternative estimates)','V','Mohanty et al., Scientific Reports — differs from Science (2025)'],
    ['385 km flow path to Bangladesh; 55 deaths, 74 missing','V','Science (2025)'],
    ['42–46 dead, >77 missing, 88,400 affected, 5,665 evacuated, 2,563 rescued, 16 bridges, 5.08 M m³ released','V','Government of Sikkim as of 8 Nov 2023 — differs from the Science figures'],
    ['13 bridges, ≈1,200 residences, >60,000 affected','V','Mohanty et al. — differs from Govt. of Sikkim counts'],
    ['Glacier retreat ≈2 km (1962–2008) and ≈400 m (2008–2019)','V','Raj et al. via Geosystems and Geoenvironment'],
    ['South Lhonak Lake at 5,200 m','V','Science (2025)'],
    ['Lake pre-event area 1.68 km², glacier area 6.9 km², slope 45°','A','inventory-scale estimates'],
    ['>200 mm antecedent rainfall; temperature anomaly +2.5 °C','A','reported but contested as a driver'],
    ['Lachen, Chungthang, Mangan, Dikchu, Singtam, Gangtok, hospital coordinates','A','gazetteer-level'],
    ['Flood & landslide polygons','A','redrawn by eye from published maps; West Bengal reach is text-only'],
    ['Routes A / B / C alignments, distances, times','A','indicative; Route B follows the Phodong–Kabi ridge'],
    ['Per-zone people counts in the Rescue Team view','S','SIMULATED — no verified live crowd sensing'],
    ['River-level slider states','S','UI demonstration only'],
  ],
},
};

const CASE_ORDER = ['np2026','in2013','in2023'];
let CURRENT_CASE = 'np2026';
const C = () => CASES[CURRENT_CASE];
